<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Modal title</h4>

</div>
<div class="modal-body">
    <div class="te">Excitavit hic ardor milites per municipia plurima, quae isdem conterminant, dispositos et castella,
        sed quisque serpentes latius pro viribus repellere moliens, nunc globis confertos, aliquotiens et dispersos
        multitudine superabatur ingenti, quae nata et educata inter editos recurvosque ambitus montium eos ut loca plana
        persultat et mollia, missilibus obvios eminus lacessens et ululatu truci perterrens.
    </div>

    <a data-toggle="modal" href="<?php echo ROOT ?>home/teste" data-target="#myModalx">Click me !</a>

    <!-- Modal -->
    <div class="modal fade" id="myModalx" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Modal title</h4>

                </div>
                <div class="modal-body">teste
                    <div class="te"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary">Save changes</button>
</div>